pcall(require, "impatient")

require "user.options"
require "user.keybindings"

require "user.plugins"
-- require "user.cmp"
require "user.coq_nvim"
require "user.lsp"
require "user.formatter"
-- require "user.lsp.null-ls"
require "user.treesitter"
require "user.telescope"
require "user.nvim_tree"
require "user.alpha"
require "user.colorizer"
require "user.comment"
require "user.autopairs"
require "user.toggleterm"
require "user.gitsigns"
require "user.project"
require "user.catppuccin"
require "user.nvim-dap"
