-- revisit github to see if colors are exposed via api
-- https://github.com/mvpopuk/inspired-github.vim
local colors = {
  red = '#ca1243',
  flamingo = '#a71d5d',
  grey = '#f5f5f5',
  light_grey = '#979BAC',
  black = '#383a42',
  white = '#ffffff',
  transparent = '#ffffff',
  light_green = '#83a598',
  orange = '#fe8019',
  green = '#8ec07c',
  yellow = '#f8eec7',
  cyan = '#489FC1',
  blue = '#0086b3',
  purple = '#795da3',
  caret = '#f5f5f5',
}

return {
  white = colors.white,
  bg = colors.white,
  bg_highlight = colors.yellow,
  normal = colors.flamingo,
  insert = colors.green,
  command = colors.cyan,
  visual = colors.yellow,
  replace = colors.flamingo,
  diffAdd = colors.green,
  diffModified = colors.cyan,
  diffDeleted = colors.flamingo,
  trace = colors.red,
  hint = colors.white,
  info = colors.blue,
  error = colors.flamingo,
  warn = colors.red,
  floatBorder = colors.black,
  selection_caret = colors.caret,
}
